classDiagram

Home <|-- Imágenes
Hilos <|-- Imágenes
Programación Creativa <|-- Imágenes
Créditos <|-- Imágenes
Mesa Expandida <|-- Imágenes
Home --o Hilos
Home --o Programación Creativa
Home --o Créditos
Home --o Mesa Expandida

Home : html | index.html
Home : css | estilos.min.css
Home : JS | scripts.js

Hilos : html | index.html
Hilos : css | estilos.min.css
Hilos : JS | scripts.js

Programación Creativa : html | index.html
Programación Creativa : css | estilos.min.css
Programación Creativa : JS | scripts.js

Créditos : html | index.html
Créditos : css | estilos.min.css
Créditos : JS | scripts.js

Mesa Expandida : html | index.html
Mesa Expandida : css | estilos.min.css
Mesa Expandida : JS | scripts.js

Imágenes : archivos .png, .jpg y .svg