version: '3.2'
services:
  bd:
    container_name: basededatos-tlc
    # image: postgis/postgis:14-3.3
    image: tobi312/rpi-postgresql-postgis:13-3.1-alpine
    restart: unless-stopped
    volumes:
      - ./basededatos:/var/lib/postgresql/data
    networks:
      - tipolitocalavera
    environment:
      POSTGRES_USER: ${BD_USUARIO}
      POSTGRES_PASSWORD: ${BD_CLAVE}
      POSTGRES_DB: ${BD_NOMBRE}

  cache:
    container_name: cache-tlc
    image: redis:6.2
    restart: unless-stopped
    networks:
      - tipolitocalavera

  tally:
    container_name: tally-tlc
    image: directus/directus:latest
    restart: unless-stopped
    ports:
      - ${CMS_PUERTO}:8055
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    networks:
      - tipolitocalavera
    depends_on:
      - cache
      - bd
    environment:
      PUBLIC_URL: ${URL_PUBLICA}
      KEY: ${CMS_LLAVE}
      SECRET: ${CMS_SECRETO}

      DB_CLIENT: 'pg'
      DB_HOST: 'basededatos-tlc'
      DB_PORT: '5432'

      DB_DATABASE: ${BD_NOMBRE}
      DB_USER: ${BD_USUARIO}
      DB_PASSWORD: ${BD_CLAVE}

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache-tlc:6379'

      ADMIN_EMAIL: ${CMS_EMAIL}
      ADMIN_PASSWORD: ${CMS_CLAVE}

networks:
  tipolitocalavera:
